### ISSUE TITLE
Pre-publication checklist

### ISSUE THREAD

**Issue by amadeuspzs** [nhsx/skunkworks-parkinsons-detection#3]
# Must have:

- [X] Permissive Open Source Licence, for example: MIT Licence
- [X] Documentation: high-level overview
- [X] Documentation: model selection
- [X] Documentation: installation and user guide
- [X] Code: file input validation
- [X] Code: legible and explainable
  - [X] Sensible variable/function names
  - [X] Complex code must be commented
  - [X] Indentation follows accepted practice
- [X] Code: modular
- [X] Security: no data shared (public data linked by URL)
- [X] Security: no serialised models
- [X] Security: no secret keys
- [ ] Web UI: implements [NHS.UK frontend](https://nhsuk.github.io/nhsuk-frontend/)

# Nice to have:

- [ ] Code: automated linting e.g. PEP8
- [X] Data: test (synthetic) data available

# Final check:

- [ ] Comms team signoff
